### ISSUE TITLE
PlotSquared API Re-Write

### ISSUE THREAD

**Issue by PenguinNexus** [help-chat/PlaceholderAPI#8]
Hiya!

Please be aware that PlotSquared have updated their API for the pre-beta version they've released, and now PlaceholderAPI needs to be updated in order to reflect this new API for MC 1.13.2

https://www.spigotmc.org/resources/plotsquared.1177/update?update=258009 for Information

**Comment by Andre601** [comment]
We are (or at least I am) aware of that.
But this Repository here isn't for this kind of issues unless it includes changes about placeholders.

You're better of asking in the repository of [PlaceholderAPI/PlaceholderAPI](/PlaceholderAPI/PlaceholderAPI), which also contains the source-code of it, to note about the changes.
But I don't quite see anything in the update, that breaks how PlaceholderAPI works, since PlaceholderAPI doesn't directly implement support for PlotSquared (In laymens terms: PlotSquared hooks into PAPI and not the other way around.)
I can be wrong about that.

But however. As long as those changes don't include updates/changes to placeholders listed in the placeholder-list, it's really better to mention this stuff in the linked repository.
